### ISSUE TITLE
continueurl not working

### ISSUE THREAD

**Issue by Jursdotme** [danielboendergaard/quickpay-v10#8]
supplying continueurl doesnt seeme to work. I just get stuck at the quickpay "Order completed" page and dont get sent back.

**Comment by danielboendergaard** [comment]
Can you show me your code creating the payment?

**Comment by Jursdotme** [comment]
It is here in: https://github.com/Jursdotme/inzite-donation/blob/master/inc/shortcode.php#L65

It is a small vue.js app in the form of a wordpress shortcode.

**Comment by danielboendergaard** [comment]
Take a look at Quickpay's docs here: https://learn.quickpay.net/tech-talk/api/services/#PUT-payments--id-link---format-

`continue_url`, `cancel_url`, `callback_url` and `language` must be in the request that creates the link, not the payment. Be aware that you have them written without the underscore in your code and you need to use `da` as the language instead of `Danish`
